import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className="h-full bg-white">
      <body className="h-full">
        {children}
      </body>
    </html>
  )
}
